### ISSUE TITLE
Getting syntax error highlight on creation of empty dictionary.

### ISSUE THREAD

**Issue by Texasbubb-work** [quidgest/vscode-velocity#16]
![image](https://github.com/quidgest/vscode-velocity/assets/167580547/fc72e4b8-21d2-403b-9f65-33ecc2a6fdb2)
Is this a bug?  I don't believe it should be marking this a syntax error on creating an empty dictionary/map.

It reads as : "mismatched input '}' expecting {'$', LCURLY, NUMBER, BOOL, '(', DQUOTE, STRING, '[', NOT}velocity"

Thanks,
G^2

**Comment by RodrigoSerafim** [comment]
Yes, its a bug. Grammar was not allowing for empty maps.
I should have it fixed in the next release.
Thx for catching that.
